#!/bin/bash

export PACKAGE_CORE_NAME="agent"
export PACKAGE_CORE_ORG="go-idp"
export PACKAGE_CORE_BIN_NAME="go-idp-agent"
export PACKAGE_CORE_VERSION="v1.12.0"

export PACKAGE_CORE_GIT_REPOSITORY="https://github.com/${PACKAGE_CORE_ORG}/${PACKAGE_CORE_NAME}"

export PACKAGE_CORE_RELEASE_DOWNLOAD="${PACKAGE_CORE_GIT_REPOSITORY}/releases/download"
